services:
  db:
    image: postgres:16-alpine
    container_name: palantir_db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: palantir_ops
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d palantir_ops"]
      interval: 3s
      timeout: 5s
      retries: 5
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/01_init.sql
      - palantir_pgdata:/var/lib/postgresql/data

  seeder:
    build:
      context: .
      dockerfile: Dockerfile.seeder
    container_name: palantir_seeder
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: palantir_ops
      DB_USER: admin
      DB_PASSWORD: password
    depends_on:
      db:
        condition: service_healthy

volumes:
  palantir_pgdata: